namespace GiftExchange.Library.Entities.Configurations;

internal class HatEntityConfiguration : IEntityTypeConfiguration<HatEntity>
{
    public void Configure(EntityTypeBuilder<HatEntity> builder)
    {
        builder.ToTable("hat");

        // DSQL has no sequences, so keys are generated by the application. Guid.CreateVersion7()
        // keeps them time-ordered, which matters more on a distributed store than it would on
        // a single node.
        builder.HasKey(hat => hat.HatId);
        builder.Property(hat => hat.HatId).HasColumnName("hat_id").ValueGeneratedNever();

        builder.Property(hat => hat.OrganizerPersonId).HasColumnName("organizer_person_id").IsRequired();
        builder.Property(hat => hat.Name).HasColumnName("name").HasMaxLength(50).IsRequired();
        builder.Property(hat => hat.NameNormalized).HasColumnName("name_normalized").HasMaxLength(50).IsRequired();
        builder.Property(hat => hat.Status).HasColumnName("status").HasMaxLength(30).IsRequired();
        builder.Property(hat => hat.AdditionalInformation).HasColumnName("additional_information").HasMaxLength(2000).IsRequired();
        builder.Property(hat => hat.PriceRange).HasColumnName("price_range").HasMaxLength(50).IsRequired();
        builder.Property(hat => hat.InvitationsQueuedAt).HasColumnName("invitations_queued_at").IsRequired();
        builder.Property(hat => hat.InvitationsSentFromIp).HasColumnName("invitations_sent_from_ip").HasMaxLength(45).IsRequired();
        builder.Property(hat => hat.CreatedAt).HasColumnName("created_at").IsRequired();

        // Mapped as a plain column with no relationship behind it. See the remarks on the property.
        builder
            .Property(hat => hat.CopiedFromHatId)
            .HasColumnName("copied_from_hat_id")
            .IsRequired();

        builder.HasIndex(hat => hat.OrganizerPersonId).HasDatabaseName("idx_hat_organizer_person");

        builder
            .HasIndex(hat => new { hat.OrganizerPersonId, hat.NameNormalized })
            .HasDatabaseName("uq_hat_organizer_name")
            .IsUnique();

        // No constraint exists in DSQL. This is configured so the model can express the
        // relationship and joins read naturally; NoAction keeps EF from inventing cascade
        // semantics the database could not honour anyway.
        builder
            .HasOne(hat => hat.Organizer)
            .WithMany(person => person.OrganizedHats)
            .HasForeignKey(hat => hat.OrganizerPersonId)
            .OnDelete(DeleteBehavior.NoAction);

        // The row meaning "no gift exchange". Its organizer is the sentinel person, so EF orders
        // the two seeds accordingly wherever a real foreign key is created.
        builder.HasData(NoRecord.Hat());
    }
}
