namespace GiftExchange.Library.Entities.Configurations;

internal class HatEntityConfiguration : IEntityTypeConfiguration<HatEntity>
{
    public void Configure(EntityTypeBuilder<HatEntity> builder)
    {
        builder.ToTable("hats");

        // DSQL has no sequences, so keys are generated by the application. Guid.CreateVersion7()
        // keeps them time-ordered, which matters more on a distributed store than it would on
        // a single node.
        builder.HasKey(hat => hat.Id);
        builder.Property(hat => hat.Id).HasColumnName("id").ValueGeneratedNever();

        builder.Property(hat => hat.OrganizerEmail).HasColumnName("organizer_email").HasMaxLength(254).IsRequired();
        builder.Property(hat => hat.OrganizerName).HasColumnName("organizer_name").HasMaxLength(100).IsRequired();
        builder.Property(hat => hat.Name).HasColumnName("name").HasMaxLength(50).IsRequired();
        builder.Property(hat => hat.NameNormalized).HasColumnName("name_normalized").HasMaxLength(50).IsRequired();
        builder.Property(hat => hat.Status).HasColumnName("status").HasMaxLength(30).IsRequired();
        builder.Property(hat => hat.AdditionalInformation).HasColumnName("additional_information").HasMaxLength(2000).IsRequired();
        builder.Property(hat => hat.PriceRange).HasColumnName("price_range").HasMaxLength(50).IsRequired();
        builder.Property(hat => hat.InvitationsQueuedAt).HasColumnName("invitations_queued_at");
        builder.Property(hat => hat.CreatedAt).HasColumnName("created_at").IsRequired();

        builder.HasIndex(hat => hat.OrganizerEmail).HasDatabaseName("idx_hats_organizer_email");

        builder
            .HasIndex(hat => new { hat.OrganizerEmail, hat.NameNormalized })
            .HasDatabaseName("uq_hats_organizer_name")
            .IsUnique();

        // No constraint exists in DSQL. This is configured so the model can express the
        // relationship and joins read naturally; NoAction keeps EF from inventing cascade
        // semantics the database could not honour anyway.
        builder
            .HasOne(hat => hat.HatStatus)
            .WithMany(status => status.Hats)
            .HasForeignKey(hat => hat.Status)
            .OnDelete(DeleteBehavior.NoAction);
    }
}
