global using System.ComponentModel.DataAnnotations;
global using System.Text;
global using System.Web;
global using LanguageExt.Common;
global using Microsoft.Extensions.DependencyInjection;
global using NamesOutOfAHat2.Interface;
global using NamesOutOfAHat2.Model;
global using NamesOutOfAHat2.Utility;
global using OsborneSupremacy.Extensions.Net.DependencyInjection;
